/**Realizar un programa que pida al usuario 2 números y se realicen las 4 operaciones básicas (Suma, resta, multiplicación, división). Imprimir los resultados. */
'use strict';

function suma(num1, num2){
    return  num1 + num2;
}
function resta(num1, num2){
    return num1 - num2;
}
function multiplicacion(num1, num2){
    return num1 * num2;
}
function division(num1, num2){
    return num1 / num2;
}
export {suma}
export {resta}
export {multiplicacion}
export {division}